experiment_name: "Regression Experiment - ModernBERT - P5 (0-4 Scale)"

# Hyperparameters
learning_rate: 1e-5
batch_size: 16
epochs: 100 # The script has Early Stopping (patience=5), so it will stop automatically when it converges.
max_len: 512

# Model Details
model_name: "modern-bert"
model_path: "answerdotai/ModernBERT-large"

# Output Directories
# I structured this to keep your regression experiments separate from the classification ones
log_dir: "exps-tuning-handle-subjectivity-no-sigma/regression-openai-modernbert-experiment-p5/logs"
checkpoint_dir: "exps-tuning-handle-subjectivity-no-sigma/regression-openai-modernbert-experiment-p5/logs/checkpoints"