experiment_name: "Experiment using LLama3 Finetuning with QlORA"
learning_rate: 1e-5
batch_size: 32
epochs: 100
model_path: "answerdotai/ModernBERT-large"
max_len: 512
model_name: "modern-bert"
log_dir: "experiments-finetuning/gemini-modernbert-qlora-p5-alpha3/logs"
checkpoint_dir: "checkpoints"